export const ACTIONS = {
  toggleBurger: 'TOGGLE_BURGER',
  toggleAccordion: 'TOGGLE_ACCORDION',
  toggleSearch: 'TOGGLE_SEARCH',
  setTerm: 'SET_TERM',
  toggleComments: 'TOGGLE_COMMENTS',
  toggleSortRule: 'TOGGLE_SORT_RULE',
  setCardsDisplay: 'SET_CARDS_DISPLAY',
  setBooks: 'SET_BOOKS',
  setCategories: 'SET_CATEGORIES',
  setBook: 'SET_BOOK',
  setLoading: 'SET_LOADING',
  setCategoriesError: 'SET_CATEGORIES_ERROR',
  setBooksError: 'SET_BOOKS_ERROR',
  setCurrBookError: 'SET_CURR_BOOK_ERROR',
};
